// Sample Data
export const doctorsData = [
    {
        id: 'doc1',
        name: 'Dr. Sarah Khan',
        specialty: 'Cardiologist',
        location: 'vijayawada',
        rating: 4,
        image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?q=80&w=600&auto=format&fit=crop',
        patients: 1200,
        experience: '15 years',
        reviews: 89,
        contact: '+1 (555) 123-4567',
        about: 'Dr. Sarah Khan is a board-certified cardiologist with over 15 years of experience in treating cardiovascular diseases. She specializes in interventional cardiology and has performed over 500 successful procedures.',
        distance: '2.5 km away'
    },
    {
        id: 'doc2',
        name: 'Dr. John Doe',
        specialty: 'Dermatologist',
        location: 'Hanuman Junction',
        rating: 5,
        image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?q=80&w=600&auto=format&fit=crop',
        patients: 800,
        experience: '12 years',
        reviews: 67,
        contact: '+1 (555) 234-5678',
        about: 'Dr. John Doe is a renowned dermatologist specializing in cosmetic dermatology and skin cancer treatment. He has helped thousands of patients achieve healthy, beautiful skin.',
        distance: '1.8 km away'
    },
    {
        id: 'doc3',
        name: 'Dr. Emily Smith',
        specialty: 'Pediatrician',
        location: 'Chicago, IL',
        rating: 4,
        image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?q=80&w=600&auto=format&fit=crop',
        patients: 1500,
        experience: '18 years',
        reviews: 124,
        contact: '+1 (555) 345-6789',
        about: 'Dr. Emily Smith is a compassionate pediatrician dedicated to providing comprehensive care for children from birth through adolescence. She believes in building lasting relationships with families.',
        distance: '3.2 km away'
    },
    {
        id: 'doc4',
        name: 'Dr. Michael Brown',
        specialty: 'Neurologist',
        location: 'Houston, TX',
        rating: 5,
        image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?q=80&w=600&auto=format&fit=crop',
        patients: 950,
        experience: '20 years',
        reviews: 78,
        contact: '+1 (555) 456-7890',
        about: 'Dr. Michael Brown is a leading neurologist specializing in stroke treatment and neurological disorders. His research has contributed to several breakthrough treatments.',
        distance: '4.1 km away'
    },
    {
        id: 'doc5',
        name: 'Dr. Jessica Jones',
        specialty: 'Oncologist',
        location: 'Phoenix, AZ',
        rating: 3,
        image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?q=80&w=600&auto=format&fit=crop',
        patients: 600,
        experience: '10 years',
        reviews: 45,
        contact: '+1 (555) 567-8901',
        about: 'Dr. Jessica Jones is an oncologist focused on providing personalized cancer treatment plans. She combines traditional and innovative approaches to patient care.',
        distance: '2.9 km away'
    },
    {
        id: 'doc6',
        name: 'Dr. Ankit Shaw',
        specialty: 'Cardiologist',
        location: 'New York, USA',
        rating: 4,
        image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?q=80&w=600&auto=format&fit=crop',
        patients: 1100,
        experience: '14 years',
        reviews: 92,
        contact: '+1 (555) 678-9012',
        about: 'Dr. Ankit Shaw is a cardiologist with expertise in preventive cardiology and heart disease management. He emphasizes lifestyle modifications alongside medical treatment.',
        distance: '1.5 km away'
    },
    {
        id: 'doc7',
        name: 'Dr. Sarah Khan',
        specialty: 'Cardiologist',
        location: 'New York, USA',
        rating: 4,
        image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?q=80&w=600&auto=format&fit=crop',
        patients: 1300,
        experience: '16 years',
        reviews: 101,
        contact: '+1 (555) 789-0123',
        about: 'Dr. Sarah Khan is a senior cardiologist with extensive experience in complex cardiac procedures. She is known for her patient-centered approach and excellent outcomes.',
        distance: '2.8 km away'
    },
    {
        id: 'doc8',
        name: 'Dr. John Doe',
        specialty: 'Dermatologist',
        location: 'Los Angeles, CA',
        rating: 5,
        image: 'https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 900,
        experience: '13 years',
        reviews: 73,
        contact: '+1 (555) 890-1234',
        about: 'Dr. John Doe is a cosmetic dermatologist specializing in anti-aging treatments and skin rejuvenation. He uses the latest technologies to achieve natural-looking results.',
        distance: '3.5 km away'
    },
    {
        id: 'doc9',
        name: 'Dr. Emily Smith',
        specialty: 'Pediatrician',
        location: 'Chicago, IL',
        rating: 4,
        image: 'https://images.pexels.com/photos/4167541/pexels-photo-4167541.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 1400,
        experience: '17 years',
        reviews: 115,
        contact: '+1 (555) 901-2345',
        about: 'Dr. Emily Smith is a pediatrician who believes in preventive care and early intervention. She works closely with parents to ensure optimal child development.',
        distance: '2.1 km away'
    },
    {
        id: 'doc10',
        name: 'Dr. Michael Brown',
        specialty: 'Neurologist',
        location: 'Houston, TX',
        rating: 5,
        image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?q=80&w=600&auto=format&fit=crop',
        patients: 1000,
        experience: '19 years',
        reviews: 85,
        contact: '+1 (555) 012-3456',
        about: 'Dr. Michael Brown is a neurologist specializing in movement disorders and epilepsy. His research has been published in leading medical journals.',
        distance: '3.8 km away'
    },
    {
        id: 'doc11',
        name: 'Dr. Jessica Jones',
        specialty: 'Oncologist',
        location: 'Phoenix, AZ',
        rating: 3,
        image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?q=80&w=600&auto=format&fit=crop',
        patients: 700,
        experience: '11 years',
        reviews: 52,
        contact: '+1 (555) 123-4567',
        about: 'Dr. Jessica Jones is an oncologist committed to providing compassionate care to cancer patients. She specializes in breast and lung cancer treatment.',
        distance: '4.3 km away'
    }
];

export const hospitalsData = [
    {
        id: 'hosp1',
        name: 'City General Hospital',
        specialty: 'General Hospital',
        location: 'New York, USA',
        rating: 5,
        image: 'https://images.pexels.com/photos/2631746/pexels-photo-2631746.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 5000,
        experience: '25 years',
        reviews: 234,
        contact: '+1 (555) 111-2222',
        about: 'City General Hospital is a state-of-the-art medical facility providing comprehensive healthcare services. We are committed to excellence in patient care and medical innovation.',
        distance: '1.2 km away'
    },
    {
        id: 'hosp2',
        name: 'Mountain View Hospital',
        specialty: 'Orthopedics Center',
        location: 'Denver, CO',
        rating: 4,
        image: 'https://images.pexels.com/photos/236380/pexels-photo-236380.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 3200,
        experience: '20 years',
        reviews: 156,
        contact: '+1 (555) 222-3333',
        about: 'Mountain View Hospital specializes in orthopedic care and sports medicine. Our team of experts provides cutting-edge treatments for bone and joint conditions.',
        distance: '2.7 km away'
    },
    {
        id: 'hosp3',
        name: 'Oceanfront Medical',
        specialty: 'Cardiology Clinic',
        location: 'Miami, FL',
        rating: 5,
        image: 'https://images.pexels.com/photos/1692693/pexels-photo-1692693.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 2800,
        experience: '18 years',
        reviews: 189,
        contact: '+1 (555) 333-4444',
        about: 'Oceanfront Medical is a premier cardiology clinic offering advanced cardiac care. Our facility is equipped with the latest technology for accurate diagnosis and treatment.',
        distance: '3.1 km away'
    },
    {
        id: 'hosp4',
        name: 'Sunrise Children\'s',
        specialty: 'Pediatrics Hospital',
        location: 'Las Vegas, NV',
        rating: 4,
        image: 'https://images.pexels.com/photos/2324837/pexels-photo-2324837.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 4100,
        experience: '22 years',
        reviews: 201,
        contact: '+1 (555) 444-5555',
        about: 'Sunrise Children\'s Hospital is dedicated to providing specialized care for children. Our child-friendly environment and expert pediatric team ensure the best care for your little ones.',
        distance: '2.3 km away'
    },
    {
        id: 'hosp5',
        name: 'Healing Touch Clinic',
        specialty: 'Clinic',
        location: 'Guntur',
        rating: 5,
        image: 'https://images.pexels.com/photos/5794040/pexels-photo-5794040.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        patients: 1800,
        experience: '15 years',
        reviews: 98,
        contact: '+1 (555) 555-6666',
        about: 'Healing Touch Clinic provides personalized healthcare services in a comfortable, welcoming environment. We focus on preventive care and wellness.',
        distance: '1.8 km away'
    },
    {
        id: 'hosp6',
        name: 'Mountain View Hospital',
        specialty: 'Orthopedics Center',
        location: 'Denver, CO',
        rating: 4,
        image: 'https://images.pexels.com/photos/236380/pexels-photo-236380.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 3500,
        experience: '21 years',
        reviews: 167,
        contact: '+1 (555) 666-7777',
        about: 'Our orthopedic center offers comprehensive care for musculoskeletal conditions. We combine traditional and innovative approaches for optimal patient outcomes.',
        distance: '3.4 km away'
    },
    {
        id: 'hosp7',
        name: 'Oceanfront Medical',
        specialty: 'Cardiology Clinic',
        location: 'Miami, FL',
        rating: 5,
        image: 'https://images.pexels.com/photos/1692693/pexels-photo-1692693.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 3000,
        experience: '19 years',
        reviews: 178,
        contact: '+1 (555) 777-8888',
        about: 'Oceanfront Medical provides world-class cardiac care with a focus on patient comfort and recovery. Our team of cardiologists is experienced in treating complex heart conditions.',
        distance: '2.9 km away'
    },
    {
        id: 'hosp8',
        name: 'Sunrise Children\'s',
        specialty: 'Pediatrics Hospital',
        location: 'Las Vegas, NV',
        rating: 4,
        image: 'https://images.pexels.com/photos/2324837/pexels-photo-2324837.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 4300,
        experience: '23 years',
        reviews: 215,
        contact: '+1 (555) 888-9999',
        about: 'Sunrise Children\'s Hospital is committed to providing exceptional pediatric care. Our facilities are designed specifically for children\'s comfort and healing.',
        distance: '2.6 km away'
    }
];
