// Doctor data
export const allDoctorsData = [
    {
        id: 101,
        name: 'Dr. Sarah Johnson',
        type: 'Cardiologist',
        distance: 1.8,
        time: 15,
        location: 'Vijayawada',
        rating: 4.9,
        reviews: 156,
        imageUrl: 'https://www.shutterstock.com/image-photo/portrait-handsome-male-doctor-stethoscope-600nw-2480850611.jpg',
        isFavorite: false,
        patients: '1,200+',
        experience: '12+',
        contact: '+91 9876543001',
        workingHours: 'Monday-Friday, 9.00 AM-6.00 PM'
    },
    {
        id: 102,
        name: 'Dr. Michael Chen',
        type: 'Dermatologist',
        distance: 2.3,
        time: 20,
        location: 'Guntur',
        rating: 4.8,
        reviews: 134,
        imageUrl: 'https://www.shutterstock.com/image-photo/portrait-handsome-male-doctor-stethoscope-600nw-2480850611.jpg',
        isFavorite: false,
        patients: '900+',
        experience: '8+',
        contact: '+91 9876543002',
        workingHours: 'Monday-Saturday, 10.00 AM-7.00 PM'
    },
    {
        id: 103,
        name: 'Dr. Emily Rodriguez',
        type: 'Pediatrician',
        distance: 3.1,
        time: 25,
        location: 'Tenali',
        rating: 4.7,
        reviews: 98,
        imageUrl: 'https://www.shutterstock.com/image-photo/portrait-handsome-male-doctor-stethoscope-600nw-2480850611.jpg',
        isFavorite: false,
        patients: '1,500+',
        experience: '15+',
        contact: '+91 9876543003',
        workingHours: 'Monday-Friday, 8.00 AM-5.00 PM'
    },
    {
        id: 104,
        name: 'Dr. David Kim',
        type: 'Neurologist',
        distance: 4.2,
        time: 35,
        location: 'Vijayawada',
        rating: 4.9,
        reviews: 187,
        imageUrl: 'https://www.shutterstock.com/image-photo/portrait-handsome-male-doctor-stethoscope-600nw-2480850611.jpg',
        isFavorite: false,
        patients: '800+',
        experience: '18+',
        contact: '+91 9876543004',
        workingHours: 'Monday-Friday, 9.00 AM-6.00 PM'
    },
    {
        id: 105,
        name: 'Dr. Lisa Thompson',
        type: 'Orthopedic',
        distance: 2.7,
        time: 22,
        location: 'Guntur',
        rating: 4.6,
        reviews: 112,
        imageUrl: 'https://www.shutterstock.com/image-photo/portrait-handsome-male-doctor-stethoscope-600nw-2480850611.jpg',
        isFavorite: false,
        patients: '1,100+',
        experience: '14+',
        contact: '+91 9876543005',
        workingHours: 'Monday-Saturday, 9.00 AM-7.00 PM'
    },
    {
        id: 106,
        name: 'Dr. James Wilson',
        type: 'Psychiatrist',
        distance: 3.8,
        time: 30,
        location: 'Tenali',
        rating: 4.8,
        reviews: 145,
        imageUrl: 'https://www.shutterstock.com/image-photo/portrait-handsome-male-doctor-stethoscope-600nw-2480850611.jpg',
        isFavorite: false,
        patients: '600+',
        experience: '16+',
        contact: '+91 9876543006',
        workingHours: 'Monday-Friday, 10.00 AM-6.00 PM'
    },
    {
        id: 107,
        name: 'Dr. Maria Garcia',
        type: 'Gynecologist',
        distance: 1.5,
        time: 12,
        location: 'Vijayawada',
        rating: 4.9,
        reviews: 203,
        imageUrl: 'https://www.shutterstock.com/image-photo/portrait-handsome-male-doctor-stethoscope-600nw-2480850611.jpg',
        isFavorite: false,
        patients: '1,800+',
        experience: '20+',
        contact: '+91 9876543007',
        workingHours: 'Monday-Saturday, 9.00 AM-6.00 PM'
    },
    {
        id: 108,
        name: 'Dr. Robert Brown',
        type: 'Urologist',
        distance: 2.9,
        time: 24,
        location: 'Guntur',
        rating: 4.7,
        reviews: 89,
        imageUrl: 'https://www.shutterstock.com/image-photo/portrait-handsome-male-doctor-stethoscope-600nw-2480850611.jpg',
        isFavorite: false,
        patients: '700+',
        experience: '11+',
        contact: '+91 9876543008',
        workingHours: 'Monday-Friday, 9.00 AM-5.00 PM'
    },
    {
        id: 109,
        name: 'Dr. Jennifer Lee',
        type: 'Endocrinologist',
        distance: 3.5,
        time: 28,
        location: 'Tenali',
        rating: 4.8,
        reviews: 167,
        imageUrl: 'https://www.shutterstock.com/image-photo/portrait-handsome-male-doctor-stethoscope-600nw-2480850611.jpg',
        isFavorite: false,
        patients: '950+',
        experience: '13+',
        contact: '+91 9876543009',
        workingHours: 'Monday-Friday, 8.00 AM-5.00 PM'
    },
    {
        id: 110,
        name: 'Dr. Thomas Anderson',
        type: 'Oncologist',
        distance: 4.8,
        time: 40,
        location: 'Vijayawada',
        rating: 4.9,
        reviews: 234,
        imageUrl: 'https://www.shutterstock.com/image-photo/portrait-handsome-male-doctor-stethoscope-600nw-2480850611.jpg',
        isFavorite: false,
        patients: '500+',
        experience: '22+',
        contact: '+91 9876543010',
        workingHours: 'Monday-Friday, 9.00 AM-6.00 PM'
    },
    {
        id: 111,
        name: 'Dr. Amanda White',
        type: 'Dentist',
        distance: 1.2,
        time: 10,
        location: 'Guntur',
        rating: 4.6,
        reviews: 178,
        imageUrl: 'https://www.shutterstock.com/image-photo/portrait-handsome-male-doctor-stethoscope-600nw-2480850611.jpg',
        isFavorite: false,
        patients: '2,100+',
        experience: '9+',
        contact: '+91 9876543011',
        workingHours: 'Monday-Saturday, 9.00 AM-7.00 PM'
    },
    {
        id: 112,
        name: 'Dr. Christopher Martinez',
        type: 'Ophthalmologist',
        distance: 2.1,
        time: 18,
        location: 'Tenali',
        rating: 4.7,
        reviews: 123,
        imageUrl: 'https://www.shutterstock.com/image-photo/portrait-handsome-male-doctor-stethoscope-600nw-2480850611.jpg',
        isFavorite: false,
        patients: '1,300+',
        experience: '17+',
        contact: '+91 9876543012',
        workingHours: 'Monday-Friday, 10.00 AM-6.00 PM'
    },
    {
        id: 113,
        name: 'Dr. Rachel Green',
        type: 'ENT Specialist',
        distance: 3.3,
        time: 27,
        location: 'Vijayawada',
        rating: 4.8,
        reviews: 156,
        imageUrl: 'https://www.shutterstock.com/image-photo/portrait-handsome-male-doctor-stethoscope-600nw-2480850611.jpg',
        isFavorite: false,
        patients: '850+',
        experience: '12+',
        contact: '+91 9876543013',
        workingHours: 'Monday-Saturday, 9.00 AM-6.00 PM'
    },
    {
        id: 114,
        name: 'Dr. Kevin Taylor',
        type: 'Pulmonologist',
        distance: 2.8,
        time: 23,
        location: 'Guntur',
        rating: 4.9,
        reviews: 198,
        imageUrl: 'https://www.shutterstock.com/image-photo/portrait-handsome-male-doctor-stethoscope-600nw-2480850611.jpg',
        isFavorite: false,
        patients: '1,100+',
        experience: '19+',
        contact: '+91 9876543014',
        workingHours: 'Monday-Friday, 9.00 AM-5.00 PM'
    },
    {
        id: 115,
        name: 'Dr. Nicole Davis',
        type: 'Rheumatologist',
        distance: 4.1,
        time: 33,
        location: 'Tenali',
        rating: 4.7,
        reviews: 87,
        imageUrl: 'https://www.shutterstock.com/image-photo/portrait-handsome-male-doctor-stethoscope-600nw-2480850611.jpg',
        isFavorite: false,
        patients: '600+',
        experience: '15+',
        contact: '+91 9876543015',
        workingHours: 'Monday-Friday, 10.00 AM-6.00 PM'
    },
    {
        id: 116,
        name: 'Dr. Daniel Clark',
        type: 'Gastroenterologist',
        distance: 1.9,
        time: 16,
        location: 'Vijayawada',
        rating: 4.8,
        reviews: 167,
        imageUrl: 'https://www.shutterstock.com/image-photo/portrait-handsome-male-doctor-stethoscope-600nw-2480850611.jpg',
        isFavorite: false,
        patients: '1,400+',
        experience: '16+',
        contact: '+91 9876543016',
        workingHours: 'Monday-Saturday, 9.00 AM-6.00 PM'
    },
    {
        id: 117,
        name: 'Dr. Stephanie Moore',
        type: 'Hematologist',
        distance: 3.7,
        time: 31,
        location: 'Guntur',
        rating: 4.9,
        reviews: 145,
        imageUrl: 'https://www.shutterstock.com/image-photo/portrait-handsome-male-doctor-stethoscope-600nw-2480850611.jpg',
        isFavorite: false,
        patients: '750+',
        experience: '18+',
        contact: '+91 9876543017',
        workingHours: 'Monday-Friday, 9.00 AM-5.00 PM'
    },
    {
        id: 118,
        name: 'Dr. Matthew Hall',
        type: 'Nephrologist',
        distance: 2.4,
        time: 20,
        location: 'Tenali',
        rating: 4.6,
        reviews: 112,
        imageUrl: 'https://www.shutterstock.com/image-photo/portrait-handsome-male-doctor-stethoscope-600nw-2480850611.jpg',
        isFavorite: false,
        patients: '800+',
        experience: '14+',
        contact: '+91 9876543018',
        workingHours: 'Monday-Friday, 10.00 AM-6.00 PM'
    },
    {
        id: 119,
        name: 'Dr. Jessica Turner',
        type: 'Dermatologist',
        distance: 1.7,
        time: 14,
        location: 'Vijayawada',
        rating: 4.7,
        reviews: 189,
        imageUrl: 'https://www.shutterstock.com/image-photo/portrait-handsome-male-doctor-stethoscope-600nw-2480850611.jpg',
        isFavorite: false,
        patients: '1,600+',
        experience: '11+',
        contact: '+91 9876543019',
        workingHours: 'Monday-Saturday, 9.00 AM-7.00 PM'
    },
    {
        id: 120,
        name: 'Dr. Ryan Phillips',
        type: 'Cardiologist',
        distance: 3.9,
        time: 32,
        location: 'Guntur',
        rating: 4.8,
        reviews: 223,
        imageUrl: 'https://www.shutterstock.com/image-photo/portrait-handsome-male-doctor-stethoscope-600nw-2480850611.jpg',
        isFavorite: false,
        patients: '1,300+',
        experience: '20+',
        contact: '+91 9876543020',
        workingHours: 'Monday-Friday, 9.00 AM-6.00 PM'
    }
]; 