// Hospital data
export const allHospitalsData = [
    {
        id: 1,
        name: 'Sunrise Health Hospital',
        type: 'Hospital',
        distance: 2.5,
        time: 40,
        location: 'Vijayawada',
        rating: 5,
        reviews: 1872,
        imageUrl: 'https://thumbs.dreamstime.com/b/hospital-building-modern-parking-lot-59693686.jpg',
        isFavorite: false,
        patients: '2,000+',
        experience: '10+',
        contact: '+91 9939069288',
        workingHours: 'Monday-Friday, 08.00 AM-18.00 PM'
    },
    {
        id: 2,
        name: 'Healing Touch Clinic',
        type: 'Clinic',
        distance: 1.2,
        time: 10,
        location: 'Guntur',
        rating: 4.9,
        reviews: 212,
        imageUrl: 'https://thumbs.dreamstime.com/b/hospital-building-modern-parking-lot-59693686.jpg',
        isFavorite: false,
        patients: '1,800+',
        experience: '12+',
        contact: '+91 9876543211',
        workingHours: 'Monday-Saturday, 9.00 AM - 7.00 PM'
    },
    {
        id: 3,
        name: 'Bright Smile Dental',
        type: 'Dental',
        distance: 3.1,
        time: 25,
        location: 'Tenali',
        rating: 4.7,
        reviews: 98,
        imageUrl: 'https://thumbs.dreamstime.com/b/hospital-building-modern-parking-lot-59693686.jpg',
        isFavorite: false,
        patients: '900+',
        experience: '7+',
        contact: '+91 9876543212',
        workingHours: 'Monday-Friday, 10.00 AM - 6.00 PM'
    },
    {
        id: 4,
        name: 'Green Leaf Ayurvedic',
        type: 'Ayurvedic',
        distance: 5.5,
        time: 45,
        location: 'Vijayawada',
        rating: 4.9,
        reviews: 301,
        imageUrl: 'https://thumbs.dreamstime.com/b/hospital-building-modern-parking-lot-59693686.jpg',
        isFavorite: false,
        patients: '2,200+',
        experience: '15+',
        contact: '+91 9876543213',
        workingHours: 'Monday-Saturday, 8.00 AM - 5.00 PM'
    },
    {
        id: 5,
        name: 'City Central Pharmacy',
        type: 'Pharmacy',
        distance: 0.8,
        time: 5,
        location: 'Guntur',
        rating: 4.5,
        reviews: 120,
        imageUrl: 'https://thumbs.dreamstime.com/b/hospital-building-modern-parking-lot-59693686.jpg',
        isFavorite: false,
        patients: '3,000+',
        experience: '5+',
        contact: '+91 9876543214',
        workingHours: 'Open 24/7'
    },
    {
        id: 6,
        name: 'Manipal Hospital',
        type: 'Hospital',
        distance: 7.2,
        time: 50,
        location: 'Vijayawada',
        rating: 4.6,
        reviews: 450,
        imageUrl: 'https://thumbs.dreamstime.com/b/hospital-building-modern-parking-lot-59693686.jpg',
        isFavorite: false,
        patients: '3,500+',
        experience: '25+',
        contact: '+91 9876543215',
        workingHours: 'Open 24/7 for Emergencies'
    },
    {
        id: 7,
        name: 'Kamineni Hospitals',
        type: 'Hospital',
        distance: 4.0,
        time: 30,
        location: 'Guntur',
        rating: 4.4,
        reviews: 320,
        imageUrl: 'https://thumbs.dreamstime.com/b/hospital-building-modern-parking-lot-59693686.jpg',
        isFavorite: false,
        patients: '2,800+',
        experience: '22+',
        contact: '+91 9876543216',
        workingHours: 'Open 24/7 for Emergencies'
    },
    {
        id: 8,
        name: 'Aayush Hospitals',
        type: 'Hospital',
        distance: 8.1,
        time: 60,
        location: 'Tenali',
        rating: 4.2,
        reviews: 280,
        imageUrl: 'https://thumbs.dreamstime.com/b/hospital-building-modern-parking-lot-59693686.jpg',
        isFavorite: false,
        patients: '2,500+',
        experience: '18+',
        contact: '+91 9876543217',
        workingHours: 'Open 24/7 for Emergencies'
    },
    {
        id: 9,
        name: 'Apollo Pharmacy',
        type: 'Pharmacy',
        distance: 1.5,
        time: 12,
        location: 'Vijayawada',
        rating: 4.6,
        reviews: 180,
        imageUrl: 'https://thumbs.dreamstime.com/b/hospital-building-modern-parking-lot-59693686.jpg',
        isFavorite: false,
        patients: '4,000+',
        experience: '10+',
        contact: '+91 9876543218',
        workingHours: 'Open 24/7'
    },
    {
        id: 10,
        name: 'Family Care Clinic',
        type: 'Clinic',
        distance: 2.8,
        time: 22,
        location: 'Guntur',
        rating: 4.8,
        reviews: 190,
        imageUrl: 'https://thumbs.dreamstime.com/b/hospital-building-modern-parking-lot-59693686.jpg',
        isFavorite: false,
        patients: '1,600+',
        experience: '9+',
        contact: '+91 9876543219',
        workingHours: 'Monday-Saturday, 9.00 AM - 8.00 PM'
    },
    {
        id: 11,
        name: 'Patanjali Ayurvedic Center',
        type: 'Ayurvedic',
        distance: 6.3,
        time: 55,
        location: 'Tenali',
        rating: 4.9,
        reviews: 250,
        imageUrl: 'https://thumbs.dreamstime.com/b/hospital-building-modern-parking-lot-59693686.jpg',
        isFavorite: false,
        patients: '2,000+',
        experience: '14+',
        contact: '+91 9876543220',
        workingHours: 'Monday-Saturday, 8.00 AM - 6.00 PM'
    },
    {
        id: 12,
        name: 'Dental World',
        type: 'Dental',
        distance: 3.9,
        time: 35,
        location: 'Vijayawada',
        rating: 4.8,
        reviews: 150,
        imageUrl: 'https://thumbs.dreamstime.com/b/hospital-building-modern-parking-lot-59693686.jpg',
        isFavorite: false,
        patients: '1,200+',
        experience: '11+',
        contact: '+91 9876543221',
        workingHours: 'Monday-Friday, 10.00 AM - 7.00 PM'
    },
    {
        id: 13,
        name: 'Metro General',
        type: 'Hospital',
        distance: 9.5,
        time: 70,
        location: 'Guntur',
        rating: 4.3,
        reviews: 500,
        imageUrl: 'https://thumbs.dreamstime.com/b/hospital-building-modern-parking-lot-59693686.jpg',
        isFavorite: false,
        patients: '4,000+',
        experience: '30+',
        contact: '+91 9876543222',
        workingHours: 'Open 24/7 for Emergencies'
    },
    {
        id: 14,
        name: 'Wellness Meds',
        type: 'Pharmacy',
        distance: 2.1,
        time: 15,
        location: 'Tenali',
        rating: 4.7,
        reviews: 110,
        imageUrl: 'https://thumbs.dreamstime.com/b/hospital-building-modern-parking-lot-59693686.jpg',
        isFavorite: false,
        patients: '2,500+',
        experience: '6+',
        contact: '+91 9876543223',
        workingHours: 'Monday-Sunday, 8.00 AM - 10.00 PM'
    },
    {
        id: 15,
        name: 'Community Clinic',
        type: 'Clinic',
        distance: 4.5,
        time: 40,
        location: 'Vijayawada',
        rating: 4.5,
        reviews: 130,
        imageUrl: 'https://thumbs.dreamstime.com/b/hospital-building-modern-parking-lot-59693686.jpg',
        isFavorite: false,
        patients: '1,400+',
        experience: '5+',
        contact: '+91 9876543224',
        workingHours: 'Monday-Friday, 9.00 AM - 5.00 PM'
    }
]; 